### PR TITLE
[color-chart] Don't show the explicit X-coord in the label, fixes #127

### LINKED ISSUE #127: [color-chart] If we include an explicit `x` via a slash it shouldn't be shown in the label
For now, we have
image
which is wrong.

### PR DESCRIPTION
**Pull request by DmitrySharabin**
image

### CODE REVIEW

File: src/color-chart/color-chart.js [hunk 1]
```diff
@@ -128,7 +129,22 @@ const Self = class ColorChart extends ColorElement {
 			ret.colors[index] = color = color.to(this.space);
 			ret.swatches.set(color, swatch);
 
-			let x = Number(name.match(/-?\d*\.?\d+$/)?.[0] ?? index);
+			let x = name.match(/-?\d*\.?\d+$/)?.[0];
+			if (x !== undefined) {
+				// Transform `Label / X-coord` to `Label`
+				// (there should be at least one space before and after the slash so the number is treated as an X-coord)
+				let regexp = new RegExp(`\\s+\\/\\s+${x}$`);
+				name = name.replace(regexp, "").trim();
```
Comment (LeaVerou) [inline src/color-chart/color-chart.js:137]: We now have the number, so we can match more efficiently, no need to check for *any* number. We can just slice by the length of the number, trim, and then check if that ends with a slash.

**Review by LeaVerou — APPROVED** [review]

File: src/color-chart/color-chart.js (hunk 1 above)
Comment (DmitrySharabin) [reply src/color-chart/color-chart.js]: Makes perfect sense. I fixed it. Thanks!
